version: 2.1

##################################################################
# WORFLOWS
##################################################################
workflows:
  despliegue_a_master:
    jobs:
      - creacion_de_docker:
          filters:
            branches:
              only: master

      - despliegue_a_heroku:
          requires:
            - creacion_de_docker
          filters:
            branches:
              only: master

##################################################################
# EXECUTORS
##################################################################
executors:
  ejecutor-base:
    machine:
      enabled: true
    working_directory: ~/proyect

##################################################################
# JOBS
##################################################################
jobs:
  creacion_de_docker:
    executor: ejecutor-base
    steps:
      - attach_workspace:
          at: ~/proyect
      - checkout
      - run:
          name: build
          command: ./scripts/docker/build.sh
      - run:
          name: push
          command: ./scripts/docker/push.sh

  despliegue_a_heroku:
    executor: ejecutor-base
    steps:
      - attach_workspace:
          at: ~/proyect
      - checkout
      - run:
          name: instalar heroku
          command: ./scripts/heroku-docker/instalar-heroku.sh
      - run:
          name: generar-dockerfile
          command: ./scripts/heroku-docker/generar-dockerfile.sh
      - run:
          name: despliegue
          command: ./scripts/heroku-docker/despliegue.sh
