version: "3.8"

services:

    json-reportes-back:
        # image: brianwolf94/json-reportes-back:latest
        image: brianwolf94/json-reportes-back:local
        container_name: json-reportes-back
        restart: on-failure:3
        env_file:
            - ./config/ambiente.env
        volumes: 
            - json-reportes-back:/usr/src/produces:rw
        ports:
            - 5000:5000
        networks: 
            - docker-net

networks:
    docker-net:
        name: docker-net
        external: false
    
volumes:
    json-reportes-back:
        name: json-reportes-back
        external: false
              