from enum import Enum


class Variable(Enum):
    VERSION = 'VERSION'
    PYTHON_HOST = 'PYTHON_HOST'
    PYTHON_PORT = 'PYTHON_PORT'
    PYTHON_EXTENSION = 'PYTHON_EXTENSION'
    NIVEL_LOGS = 'NIVEL_LOGS'
    DIRECTORIO_LOGS = 'DIRECTORIO_LOGS'
    DIRECTORIO_SISTEMA_ARCHIVOS = 'DIRECTORIO_SISTEMA_ARCHIVOS'
    DB_SQLITE_SCRIPT = 'DB_SQLITE_SCRIPT'
    DB_SQLITE_RUTA = 'DB_SQLITE_RUTA'


_no_mostrar = []
