from enum import Enum


class Variable(Enum):
    VERSION = 'VERSION'
    PYTHON_HOST = 'PYTHON_HOST'
    PYTHON_PORT = 'PYTHON_PORT'
    NIVEL_LOGS = 'NIVEL_LOGS'
    DIRECTORIO_LOGS = 'DIRECTORIO_LOGS'
    DIRECTORIO_SISTEMA_ARCHIVOS = 'DIRECTORIO_SISTEMA_ARCHIVOS'
    DIRECTORIO_TEMP = 'DIRECTORIO_TEMP'
    DB_SQLITE_SCRIPT = 'DB_SQLITE_SCRIPT'
    DB_SQLITE_RUTA = 'DB_SQLITE_RUTA'
    DB_TIPO = 'DB_TIPO'


_no_mostrar = []
