-----------------------------------------------
-- BORRADO DE TABLAS
-----------------------------------------------

DROP TABLE IF EXISTS MODELOS;
DROP TABLE IF EXISTS REPORTES;
DROP TABLE IF EXISTS TIPOS_CREADOR;
DROP TABLE IF EXISTS ARCHIVOS;


-----------------------------------------------
-- CREACION DE TABLAS
-----------------------------------------------

CREATE TABLE MODELOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	DESCRIPCION TEXT(256)
);


CREATE TABLE REPORTES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	MODELO_ID INTEGER NOT NULL,
	FOREIGN KEY(ID) REFERENCES MODELOS(ID)
);


CREATE TABLE TIPOS_CREADOR (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE
);


CREATE TABLE ARCHIVOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	DESCRIPCION TEXT(256),
	DIRECTORIO TEXT(512) NOT NULL,
	ID_CREADOR INTEGER NOT NULL,
	ID_TIPO_CREADOR INTEGER NOT NULL,
	FOREIGN KEY(ID) REFERENCES MODELOS(ID)
);


-----------------------------------------------
-- INSERTS
-----------------------------------------------
INSERT INTO TIPOS_CREADOR (NOMBRE) VALUES('MODELO');
INSERT INTO TIPOS_CREADOR (NOMBRE) VALUES('REPORTE');




















