-----------------------------------------------
-- BORRADO DE TABLAS
-----------------------------------------------

DROP TABLE IF EXISTS MODELOS;
DROP TABLE IF EXISTS ARCHIVOS;


-----------------------------------------------
-- CREACION DE TABLAS
-----------------------------------------------

CREATE TABLE MODELOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	DESCRIPCION TEXT(256)
);


CREATE TABLE ARCHIVOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	DIRECTORIO_RELATIVO TEXT(512) NOT NULL,
	TIPO TEXT NOT NULL,
	ID_MODELO INTEGER NOT NULL,
	FOREIGN KEY(ID) REFERENCES MODELOS(ID)
);


















