-----------------------------------------------
-- BORRADO DE TABLAS
-----------------------------------------------

DROP TABLE IF EXISTS MODELOS;
DROP TABLE IF EXISTS REPORTES;
DROP TABLE IF EXISTS TIPOS_CREADORES;
DROP TABLE IF EXISTS ARCHIVOS;


-----------------------------------------------
-- CREACION DE TABLAS
-----------------------------------------------

CREATE TABLE MODELOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	DESCRIPCION TEXT(256)
);


CREATE TABLE REPORTES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	MODELO_ID INTEGER NOT NULL,
	FOREIGN KEY(ID) REFERENCES MODELOS(ID)
);


CREATE TABLE ARCHIVOS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE TEXT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	RUTA_RELATIVA TEXT(512) NOT NULL,
	TIPO_CREADOR TEXT NOT NULL,
	ID_CREADOR INTEGER NOT NULL,
	FOREIGN KEY(ID) REFERENCES MODELOS(ID)
);


















